# -*- coding: utf-8 -*-
"""draw_data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YJpIHV_0ueCP8yKwlGQNmjd714CP3OQn
"""

#데이터 분석과 데이터 그래프 그리기위한 라이브러리 선언
import matplotlib.pyplot as plt
import numpy as np


fig = plt.figure()
ax = fig.add_subplot(111,projection='3d')
n = 5
arr = np.random.randint(0,10000,size=n*n)

#reshape((n,m)) 을 이용해서 행렬의 형태를 바꿀 수 있다.



X = [ i for i in range(n) for _ in range(n)]
Y = [ i for _ in range(n) for i in range(n)]
Z = arr
print(X)
print(Y)
print(Z)

ax.scatter(X,Y,Z)

ax.set_xlabel('X')
ax.set_ylabel('Y')
ax.set_zlabel('Z')
plt.suptitle('random')
ax.view_init(0,90)#보는 각도
plt.show()



